# conda env create|update --file environment.yml
name: Swim
dependencies:
- python=3.6
- pip
- pip:
  - '--editable=.'
  - flake8
  - flake8-quotes
  - jupyter
  - matplotlib
  - nltk
  - numpy==1.16.*
  - pandas==0.24.1
  - pytest
  - pytest-mock
  - scipy
  - seaborn
  - sklearn
  - graphviz==0.10.*
  - torch
